#logging:
#  level:
#    org.springframework: debug
spring:
  datasource:
    url: jdbc:h2:file:./db/mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        discriminator:
          ignore_explicit_for_joined: true
  h2:
    console:
      enabled: true

logging:
  level:
    com.roger.mmst: debug